### ISSUE TITLE
Property name "color" of background is misleading

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/TLF-Library#103]
When setting tpConfig$background$innerBackground$color <- "yellow" I would expect a yellow inner background, but just the borderlines are yellow. To set the color of the background I need to use the property "fill".

What about renaming the current "color" to "borderColor", if this is of interest at all?
And to rename "fill" to "fillColor" or just "color"?

**Comment by msevestre** [comment]
@pchelle what it the nomenclature in ggplot? I believe we should follow the exact same nomenclature so that user know what to expect.

Unless obviously this does not exist in ggplot to which case we should agree on naming

**Comment by pchelle** [comment]
I was using the ggplot nomenclature where "color" defines the border and "fill" the inner part:
In ggplot, the background is defined by "element_rect()" with 4 properties: "fill", "color", "linetype" and "size". Except "fill", the other properties defines only the border.
