### ISSUE TITLE
How can I set the linetype and color of a timeprofile in a simple example?

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/TLF-Library#104]
With a simple restriction to 10 data points of the test data set I get the following plot by the following code.
How can I display a green dashed line between the data points?
I did not find any options in the plot configuration for that.
```
timeProfileMapping <- TimeProfileDataMapping$new(x = "Time", y = variableNames[7])

data1_10 <- outputValues$data[226:235,]

tpConfig <- TimeProfilePlotConfiguration$new(title = "my Plot",
                                             data = data1_10, metaData = outputValues$metaData,
                                             dataMapping = timeProfileMapping)
tpConfig$background$innerBackground$color <- "red"
tpConfig$background$innerBackground$fill <- "yellow"

# Plot Time Profile
timeProfilePlot <- plotTimeProfile(
  data = data1_10,
  metaData = outputValues$metaData,
  dataMapping = timeProfileMapping,
  plotConfiguration = tpConfig
)

timeProfilePlot
```
![grafik](https://user-images.githubusercontent.com/25579536/73255073-d36e4680-41bf-11ea-8ecc-9b7c5fabb863.png)

**Comment by Yuri05** [comment]
@abdullahhamadeh

**Comment by pchelle** [comment]
Unfortunately, I don't think this is doable with the current version of the plotTimeProfile.
Currently, points are plot has default and if a linetype is used to group the data, there is only a line and no points anymore.

I have started creating atom plots that should help fixing this: the time profile will merge lines and points atom plots. If only points or lines have to be output, the value "blank" will be the plot configuration option.
