### ISSUE TITLE
Timeprofile plot mapping => leads to inconsistent plots

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/TLF-Library#108]
The current implemetation and description are inconsistent. 
mapping ymax and ymin and using timeprofileplotconfiguration leads to Rangeplot.
mapping y, ymax and ymin and using timeprofileplotconfiguration leads to plot woth error plot. Here it should be Rengeplot with y as additional line.

**Comment by msevestre** [comment]
@abdullahhamadeh @pchelle 
How is this supposed to work?
