### ISSUE TITLE
Installation warning (Linux)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#115]
1.0.61 
`Warning: /tmp/RtmpGmmma5/R.INSTALL3ef57825e1e0/tlf/man/grapes-or-or-grapes.Rd: \name should not contain !, | or @`

![grafik](https://user-images.githubusercontent.com/25061876/76855281-17d9a280-6851-11ea-8187-4a0fba2c68be.png)

**Comment by IndrajeetPatil** [comment]
This is no longer relevant as there is no more `grapes-or-or-grapes.Rd` in `man` [folder](https://github.com/Open-Systems-Pharmacology/TLF-Library/tree/develop/man).

The `%||%` operator now lives in _ospsuite.utils_.
