### ISSUE TITLE
Methods for second y-axis

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/TLF-Library#122]

**Comment by pchelle** [comment]
I am thinking of using `cowplot` to create dual y-axis by merging 2 plots into one: https://wilkelab.org/cowplot/articles/aligning_plots.html
@abdullahhamadeh , thoughts ?

**Comment by abdullahhamadeh** [comment]
@pchelle looks promising.  Is it part of validR?

**Comment by pchelle** [comment]
Closing this issue in favor of issue #392
