### ISSUE TITLE
Legend for "lines" in population time profile plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#138]
@Yuri05 commented on [Thu Feb 18 2021](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/429)

At the moment legend entries for mean, median etc. in population time profile plots are shown like below.
![grafik](https://user-images.githubusercontent.com/25061876/108358039-873cdc80-71ee-11eb-88fb-b292fec63c6b.png)

USers find it irritating.
Is it possible to show the legend entries in a "more convenient way"?
![grafik](https://user-images.githubusercontent.com/25061876/108358459-0a5e3280-71ef-11eb-8f70-c768f1b68617.png)

**Comment by pchelle** [comment]
Fixed with PR #137
