### ISSUE TITLE
Closer integration of TLF with ospsuite-r

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/TLF-Library#143]
Unless there are some strong reasons to avoid dependency of TLF on ospsuite-r, I would propose a closer integration of the packages, including implementing default figure creation using simulation outputs and the DataRepository objects loaded from pkml. What are your thoughts on this?

Maybe we can integrate some approaches we implemented in esqlabs-package. E.g., we have workflows for creating time-values figures using simulation outputs, predicted-vs-observed, etc...

**Comment by PavelBal** [comment]
@msevestre @abdullahhamadeh @pchelle @Yuri05

**Comment by IndrajeetPatil** [comment]
Closed in favour of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/674
