### ISSUE TITLE
use `{patchwork}` instead of `{gridExtra}` to create a plot grid

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#164]
I can take care of this change.

For more, see: https://www.data-imaginist.com/2019/patch-it-up-and-send-it-out/

This is a direct replacement with not much change needed in terms of argument specification:

```r
library(patchwork)
library(gridExtra)
library(ggplot2)

p1 <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
p2 <- ggplot(iris, aes(Sepal.Length, Sepal.Width)) + geom_point()

grid.arrange(p1, p2, ncol = 2)
wrap_plots(p1, p2, ncol = 2)
```

**Comment by pchelle** [comment]
`patchwork` (and also `cowplot`) is not included in the list of validR functions, so not sure if we may use it or not.
@Yuri05 , thoughts ?

**Comment by IndrajeetPatil** [comment]
It's not a hard dependency (we just suggest it, not import it), so _maybe_ it will be okay?

**Comment by Yuri05** [comment]
should be ok. also in the next valid R version those packages will be supported (s. below)

<details><summary>supported packages next version (based on R 4.0.4)</summary>

Package |Version
-|-
accelmissing|1.4
acepack|1.4.1
ade4|1.7-16
affy|1.68.0
amap|0.8-18
AnnotationDbi|1.52.0
aod|1.3.1
argonDash|0.2.0
argonR|0.2.0
asd|2.2
askpass|1.1
assertr|2.8
assertthat|0.2.1
aws.ec2metadata|0.2.0
aws.s3|0.3.21
aws.signature|0.6.0
base|4.0.4
base64enc|0.1-3
beeswarm|0.3.1
BH|1.75.0-0
binom|1.1-1
binr|1.1
Biobase|2.50.0
BiocGenerics|0.36.1
BiocManager|1.30.12
biomaRt|2.46.3
bit64|4.0.5
bitops|1.0-6
bookdown|0.21
bookdownplus|1.5.8
boot|1.3-27
bpp|1.0.0
brms|2.15.0
broom|0.7.6
bs4Dash|0.5.0
bsplus|0.1.2
Cairo|1.5-12.2
calibrate|1.7.7
callr|3.6.0
captioner|2.2.3
car|3.0-10
caret|6.0-86
caTools|1.18.2
CBPS|0.22
chemometrics|1.4.2
circlize|0.4.12
class|7.3-18
cli|2.4.0
clinfun|1.0.15
cluster|2.1.2
cmprsk|2.2-10
cobalt|4.3.1
coda|0.19-4
codetools|0.2-18
colorspace|2.0-0
colourpicker|1.1.0
combinat|0.0-8
compiler|4.0.4
ComplexHeatmap|2.6.2
corrplot|0.84
corrr|0.4.3
COUNT|1.3.4
covr|3.5.1
cowplot|1.1.1
coxphf|1.13.1
coxphw|4.0.2
coxrobust|1
curl|4.3
cutpointr|1.1.0
cvTools|0.3.2
data.table|1.14.0
DataExplorer|0.8.2
datasets|4.0.4
DBI|1.1.1
dbplyr|2.1.1
DEGseq|1.44.0
dendextend|1.14.0
desc|1.3.0
descr|1.1.5
DescTools|0.99.41
deSolve|1.28
devEMF|4.0-2
devtools|2.4.0
dfcomb|3.0-0
dfcrm|0.2-2.1
dfoptim|2020.10-1
DiagrammeR|1.0.6.1
dials|0.0.9
dichromat|2.0-0
diffdf|1.0.4
digest|0.6.27
dlm|1.1-5
dmutate|0.1.2
doBy|4.6.9
doMC|1.3.7
doParallel|1.0.16
doRNG|1.8.2
DoseFinding|0.9-17
dplyr|1.0.5
drc|3.0-1
DT|0.18
dtplyr|1.1.0
e1071|1.7-6
ebal|0.1-6
echarts4r|0.4.0
edgeR|3.32.1
emmeans|1.5.5-1
entropy|1.2.1
epiR|2.0.19
eRm|1.0-2
etm|1.1.1
evaluate|0.14
ezknitr|0.6
fable|0.3.0
factoextra|1.0.7
FactoInvestigate|1.7
FactoMineR|2.4
feasts|0.2.1
fields|11.6
fitdistrplus|1.1-3
flexdashboard|0.5.2
flexsurv|2
flextable|0.6.5
forcats|0.5.1
foreach|1.5.1
forecast|8.14
foreign|0.8-81
forestplot|1.10.1
formatR|1.9
formattable|0.2.1
Formula|1.2-4
fpc|2.2-9
frailtypack|3.3.2
fs|1.5.0
furrr|0.2.2
future|1.21.0
future.apply|1.7.0
fuzzyjoin|0.1.6
gam|1.2
gbm|2.1.8
generics|0.1.0
getPass|0.2-2
GGally|2.1.1
gganimate|1.0.7
ggbeeswarm|0.6.0
ggforce|0.3.3
ggfortify|0.4.11
GGIR|2.3-0
ggmap|3.0.0
ggmcmc|1.5.1.1
ggmosaic|0.3.3
ggplot2|3.3.3
ggplotify|0.0.5
ggrepel|0.9.1
ggstance|0.3.5
ggthemes|4.2.4
glmnet|4.1-1
glue|1.4.2
gmodels|2.18.1
goftest|1.2-2
goodpractice|1.0.2
googledrive|1.0.1
googlesheets|0.3.0
googlesheets4|0.3.0
GPArotation|2014.11-1
gplots|3.1.1
graphics|4.0.4
grDevices|4.0.4
grid|4.0.4
gridBase|0.4-7
gridExtra|2.3
gsDesign|3.2.0
gtable|0.3.0
hardhat|0.1.5
haven|2.4.0
heatmaply|1.2.1
here|1.0.1
hexbin|1.28.2
highr|0.9
Hmisc|4.5-0
hms|1.0.0
htmlTable|2.1.0
htmltools|0.5.1.1
htmlwidgets|1.5.3
httr|1.4.2
import|1.2.0
infer|0.5.4
iptools|0.6.1
IRanges|2.24.1
iterators|1.0.13
itertools|0.1-3
janitor|2.1.0
JM|1.4-8
jsonlite|1.7.2
kableExtra|1.3.4
keras|2.4.0
KernSmooth|2.23-18
knitr|1.32
labeling|0.4.2
labelled|2.8.0
later|1.1.0.1
lattice|0.20-41
latticeExtra|0.6-29
lavaan|0.6-8
lazyeval|0.2.2
lda|1.4.2
LDAvis|0.3.2
leaflet|2.0.4.1
lifecycle|1.0.0
limma|3.46.0
lintr|2.0.1
lme4|1.1-26
lmerTest|3.1-3
log4r|0.3.2
logistf|1.24
lsmeans|2.30-0
lubridate|1.7.10
magrittr|2.0.1
mailR|0.4.1
markdown|1.1
MASS|7.3-53.1
Matching|4.9-9
MatchIt|4.1.0
Matrix|1.3-2
mclust|5.4.7
mcmc|0.9-7
MCMCpack|1.5-0
MCPMod|1.0-10.1
mcr|1.2.1
Mediana|1.0.8
memoise|2.0.0
meta|4.18-0
metafor|2.4-0
methods|4.0.4
mgcv|1.8-35
mice|3.13.0
miceadds|3.11-6
microbenchmark|1.4-7
minpack.lm|1.2-1
mkin|1.0.3
MLmetrics|1.1.1
mlr|2.19.0
mnormt|2.0.2
modelr|0.1.8
mrgsolve|0.11.0
mschart|0.3.0
mstate|0.3.1
muhaz|1.2.6.3
multcomp|1.4-16
multcompView|0.1-8
munsell|0.5.0
mvna|2.0.1
mvtnorm|1.1-1
ncappc|0.3.0
ngram|3.0.4
nlme|3.1-152
nlmeODE|1.1
nnet|7.3-15
NonCompart|0.4.7
nonmem2R|0.2.3
nortest|1.0-4
numDeriv|2016.8-1.1
odbc|1.3.2
odeintr|1.7.1
officer|0.3.18
openssl|1.4.3
openxlsx|4.2.3
optimx|2020-4.2
outliers|0.14
pander|0.6.3
parallel|4.0.4
parsedate|1.2.0
parsnip|0.1.5
party|1.3-7
partykit|1.2-13
patchwork|1.1.1
pcaMethods|1.82.0
penalized|0.9-51
pharmaRTF|0.1.2
pheatmap|1.0.12
PK|1.3-5
pkgload|1.2.1
PKPDmodels|0.3.2
plot3D|1.3
plotly|4.9.3
plotrix|3.8-1
plotROC|2.2.1
plsdepot|0.1.17
plsgenomics|1.5-2
plspm|0.4.9
plumber|1.1.0
plyr|1.8.6
PMCMRplus|1.9.0
png|0.1-7
PopED|0.5.0
powerSurvEpi|0.1.3
ppcor|1.1
prettyR|2.2-3
prettyunits|1.1.1
printr|0.1.1
pROC|1.17.0.1
processx|3.5.1
prodlim|2019.11.13
profvis|0.3.7
progress|1.2.2
promises|1.2.0.1
PropCIs|0.3-0
proto|1.0.0
pryr|0.1.4
pspline|1.0-18
psych|2.1.3
purrr|0.3.4
pwr|1.3-0
qcc|2.7
qdap|2.4.3
qualityTools|1.55
qvalue|2.22.0
r2d3|0.2.5
R6|2.5.0
randomForest|4.6-14
randomForestSRC|2.11.0
ranger|0.12.1
raster|3.4-5
RBesT|1.6-1
RColorBrewer|1.1-2
Rcpp|1.0.6
RcppAlgos|2.4.1
readr|1.4.0
readxl|1.3.1
recipes|0.1.16
remotes|2.3.0
reprex|2.0.0
reshape|0.8.8
reshape2|1.4.4
reticulate|1.18
Rfit|0.24.2
rhandsontable|0.3.7
RISCA|0.9
RJSONIO|1.3-1.4
rlang|0.4.10
rmarkdown|2.7
rmdshower|2.1.1
Rmisc|1.5
Rmpi|0.6-9.1
rms|6.2-0
RMySQL|0.10.21
RNMGraphics|4.0-7
RNMImport|4.0-32
robust|0.5-0.0
ROC|1.66.0
ROCR|1.0-11
roxygen2|7.1.1
rpact|3.0.4
rpart|4.1-15
rprojroot|2.0.2
rsample|0.0.9
rsconnect|0.8.17
RSelenium|1.7.7
RSQLite|2.2.6
rstan|2.21.2
rstanarm|2.21.1
rtf|0.4-14.1
Rtsne|0.15
runjags|2.2.0-2
rvest|1.0.0
rvg|0.2.5
RxODE|1.0.8
S4Vectors|0.28.1
sandwich|3.0-0
sas7bdat|0.5
SASxport|1.7.0
scales|1.1.1
sendmailR|1.2-1
seriation|1.2-9
sessioninfo|1.1.1
shape|1.4.5
shiny|1.6.0
shinyalert|2.0.0
shinyBS|0.61
shinybusy|0.2.2
shinycssloaders|1.0.0
shinydashboard|0.7.1
shinyjs|2.0.0
shinytest|1.5.0
shinythemes|1.2.0
shinyTree|0.2.7
shinyWidgets|0.6.0
SixSigma|0.9-52
skimr|2.1.3
slam|0.1-48
slider|0.2.1
snowfall|1.84-6.1
sparklyr|1.6.2
spatial|7.3-13
spelling|2.2
splines|4.0.4
splines2|0.4.2
sqldf|0.4-11
ssh|0.7.0
stargazer|5.2.2
stats|4.0.4
stats4|4.0.4
stringdist|0.9.6.3
stringi|1.5.3
stringr|1.4.0
styler|1.4.1
surv2sampleComp|1.0-5
survey|4
survival|3.2-10
survminer|0.4.9
survRM2|1.0-3
svglite|2.0.0
tableone|0.12.0
tables|0.9.6
tcltk|4.0.4
tensorflow|2.4.0
testthat|3.0.2
textrecipes|0.4.0
tibble|3.1.1
tidymodels|0.1.3
tidyposterior|0.1.0
tidypredict|0.4.8
tidyr|1.1.3
tidyselect|1.1.0
tidytext|0.3.1
tidyverse|1.3.1
timereg|1.9.8
tinytex|0.31
tm|0.7-8
tokenizers|0.2.1
tools|4.0.4
topicmodels|0.2-12
treemap|2.4-2
TriMatch|0.9.9
tseries|0.10-48
tsfeatures|1.0.2
tsibble|1.0.1
tsne|0.1-3
TTR|0.24.2
tukeytrend|0.7
tune|0.1.3
ucminf|1.1-4
usethis|2.0.1
utils|4.0.4
venn|1.1
VennDiagram|1.6.20
VGAM|1.1-5
VIM|6.1.0
vipor|0.4.5
viridis|0.6.0
viridisLite|0.4.0
vpc|1.2.2
vrwatch|1.0.1
wavelets|0.3-0.2
WeightIt|0.12.0
whisker|0.4
withr|2.4.2
workflows|0.2.2
writexl|1.3.1
xlsx|0.6.5
XML|3.99-0.6
xml2|1.3.2
xpose4|4.7.1
xtable|1.8-4
yaml|2.2.1
yardstick|0.0.8
zeallot|0.1.0
zip|2.1.1
zoo|1.8-9
</details>
