### ISSUE TITLE
updating git submodule

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#184]
The `{tlf}` git submodule for `build-scripts` is at the following commit:

![image](https://user-images.githubusercontent.com/11330453/138065046-12f1c9c5-7543-4ca9-819d-d9f7163cf421.png)

But the submodule repo has been updated since then:

![image](https://user-images.githubusercontent.com/11330453/138065369-6dd3ca8f-c427-452f-81f4-ab59f57b494f.png)

How can we update the `\scripts` folder to use the latest commit?

```git
git submodule update --init --recursive
```

**Comment by Yuri05** [comment]
I usually do git pull on the submodules folder (so here: on the \scripts folder) - which updates this particular submodule to the latest version.
