### ISSUE TITLE
possible vignette about interfacing with `{ospsuite}`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#202]
Although the current vignettes do an excellent job of explaining how to use the individual plotting functions and modifying them further, I am still a bit confused about how these functions interface with objects from `{ospsuite}` package.

I am guessing you are already doing this in your workflows at Bayer? 

It will be really useful to have a vignette that addresses this point. What do you think?

**Comment by msevestre** [comment]
@IndrajeetPatil This is all work that needs to be done in fact. What is defined in the OSPSuite.ReportingEngine can probably be reused `to some extent` , but I almost feel it would be better to start fresh from the perspective of the OSPSuite. How to implement the basic plots using the tlf.
We can discuss this tomorrow

**Comment by pchelle** [comment]
@IndrajeetPatil 
The file [R/utilities-goodness-of-fit.R ](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/98abeafa2f061421624ba531c7848cc274b427e6/R/utilities-goodness-of-fit.R) includes the mean and population functions that format and plot simulated and observed data as time profiles, obs vs pred and residuals.
The code is dense, but this might be a good place to start to know what to use for interfacing the `{ospsuite}` package

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/674
