### ISSUE TITLE
vignette broken image links

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/TLF-Library#206]
@IndrajeetPatil 
Image links of vignettes [plot-maker](https://www.open-systems-pharmacology.org/TLF-Library/articles/plot-maker.html) and [theme-maker](https://www.open-systems-pharmacology.org/TLF-Library/articles/theme-maker.html) do not seem to work

Is it from the documentation build or do I need to locate and call the images from `inst/extdata` ?

**Comment by IndrajeetPatil** [comment]
Hmm, for some reason, this issue keeps coming back.

Let me have a look. A lot has changed in the new version of pkgdown, and so it might have something to do with that.
