### ISSUE TITLE
Can't reproduce examples from `setXAxis` docs

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#220]
I have a hunch that this has something to do with updates to `isIncluded` function in the latest version of _ospsuite.utils_.

# what the outputs used to look like

![image](https://user-images.githubusercontent.com/11330453/155503676-c3bf127d-592f-4f1f-8712-2f92a762ac7b.png)

# what they look like now

The axes labels are different.

``` r
library(tlf)

myPlot <- addLine(x = c(1, 2, 3), y = c(10, 50, 100))

setXAxis(myPlot, scale = Scaling$log)
```

![](https://i.imgur.com/Y04KpEn.png)

``` r
setXAxis(myPlot, ticks = c(1, 2, 3), ticklabels = parse(text = c("alpha", "beta", "gamma")))
```

![](https://i.imgur.com/GNJCw1Y.png)

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by pchelle** [comment]
I think you are right.
`parse(text = c("alpha", "beta", "gamma"))` creates a vector of type expression which is not a base object type and gets an error.
In the `{tlf}` function `createPlotTicks`, `isOfType` is assessed after `isIncluded` so I can swap those and prevent the error
