### ISSUE TITLE
Use minimal theme by default ? 

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#223]
IMHO, most of the defaults for _tlf_ plot themes are unnecessarily complex. I would personally recommend scaling down this complexity and adopting more minimal themes, which are easier for the reader to understand. 

I know that the users can use their own theme to customize the plots, but we should be doing whatever we can to provide custom settings that reduces this extra work for the user. 

For example, [box plot](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotBoxWhisker.html) defaults

![image](https://user-images.githubusercontent.com/11330453/156736494-17fa003e-0a89-4b23-95d0-690ce570aac7.png)

Can be something like this:

``` r
library(ggplot2)

boxData <- data.frame(x = c(rep("A", 500), rep("B",500)), y = rlnorm(1000))

ggplot(boxData, aes(x, y)) +
  geom_boxplot() +
  theme_minimal()
```

![](https://i.imgur.com/bO8zScG.png)

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Here is another example with [histogram](https://www.open-systems-pharmacology.org/TLF-Library/reference/plotHistogram.html)

![image](https://user-images.githubusercontent.com/11330453/156738000-db86bea1-4b61-434f-aa6c-a3c73b12e5d3.png)

which, with a minimal theme, can look something like the following:

``` r
library(ggplot2)

histData <- data.frame(x = rnorm(100))

ggplot(histData, aes(x)) +
  geom_histogram(color = "black") +
  theme_minimal()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/SrNROvf.png)

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by IndrajeetPatil** [comment]
[Alternatively](https://www.psiweb.org/docs/default-source/2018-psi-conference-posters/48-julie-jones.pdf), you can also just soften the existing grid:

![image](https://user-images.githubusercontent.com/11330453/157617089-c363ed99-8839-46c2-8e93-07032768e017.png)

**Comment by PavelBal** [comment]
@IndrajeetPatil I like your suggestions for the default plots.

Also - no grid by default.
