### ISSUE TITLE
Define export config parameter defaults in the tlf environment

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#237]
Otherwise, we need to explicitly set some default arguments for these parameters:

```r
plotSaveFileFormat = "png",
plotSaveFileWidth = 16,
plotSaveFileHeight = 9,
plotSaveFileDimensionUnits = "cm"
```

**Comment by msevestre** [comment]
Why don't?
Shouldn't they have predefined values instead?

**Comment by IndrajeetPatil** [comment]
Sorry, mangled the issue title. Created during a call with Pierre.

I agree with you.
