### ISSUE TITLE
Cannot install ospsuite.utils

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#241]
https://github.com/Open-Systems-Pharmacology/TLF-Library/runs/6004849722?check_suite_focus=true#step:4:48
```
Error: Error: <callr_remote_error: Cannot install packages:
  * local::.: Can't install dependency ospsuite.utils
  * ospsuite.utils: Can't find package called ospsuite.utils.>
   in process 8537 
  -->
  <simpleError: Cannot install packages:
  * local::.: Can't install dependency ospsuite.utils
  * ospsuite.utils: Can't find package called ospsuite.utils.>
```

**Comment by IndrajeetPatil** [comment]
This is because we archived _ospsuite.utils_ from CRAN (cf. https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/106#issuecomment-1089200141), and so now it's available only on GitHub.

Trying a few things here: https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/242

**Comment by IndrajeetPatil** [comment]
We have removed GHA from our workflows now.
