### ISSUE TITLE
`LabelConfiguration` parameters don't follow lowerCamel case convention

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#243]
Here: https://www.open-systems-pharmacology.org/TLF-Library/reference/LabelConfiguration.html

## Current

```r
LabelConfiguration$new(
  title = NULL,
  subtitle = NULL,
  xlabel = NULL,
  ylabel = NULL
)
```

## Proposed

```r
LabelConfiguration$new(
  title = NULL,
  subtitle = NULL,
  xLabel = NULL,
  yLabel = NULL
)
```

@pchelle, @Yuri05 What do you think? Or is it too late to make this change?

**Comment by pchelle** [comment]
Here, I think it is less confusing to keep names consistent with `{ggplot2}` (that uses `xlabel` and `ylabel`)

**Comment by IndrajeetPatil** [comment]
Fair enough.
