### ISSUE TITLE
Is `font` parameter redundant in `Label` constructor?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#261]
@pchelle can correct me if I am wrong here, but `font` parameter is redundant here. 

I am specifying `tlf::Label` object here which already specifies all aesthetic properties for the font

```r
tlf::Label$new(
  text = "",
  font = NULL,
  color = NULL,
  size = NULL,
  fontFace = NULL,
  fontFamily = NULL,
  angle = NULL,
  align = NULL
)
```

that `tlf::Font` object would do:

```r
tlf::Font$new(
  color = NULL,
  size = NULL,
  fontFamily = NULL,
  fontFace = NULL,
  angle = NULL,
  align = NULL
)
```

So, it is not necessary to specify argument for this parameter.

_Originally posted by @IndrajeetPatil in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/871#discussion_r866605549_

**Comment by pchelle** [comment]
Not necessarily redundant. 
This aims at providing more freedom to users as they can provide a `Font` object directly or font properties on the fly or a mix of both (in which case the non-`null` font properties will overwrite the properties of the `Font` object)

**Comment by pchelle** [comment]
A use case of the last configuration would be users who want to create a "base font" and then just overwrite its size or color only

**Comment by IndrajeetPatil** [comment]
Got it! Thanks for the explanation. Just wanted to make sure that this was by design.
