### ISSUE TITLE
Introduce `ResVsPredPlotConfiguration` class for `plotResVsPred()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#262]
Most of the plotting functions in `{tlf}` have their own corresponding plot configuration classes:
- `plotObsVsPred()` ⇔ `ObsVsPredPlotConfiguration`
- `plotHistogram()` ⇔ `HistogramPlotConfiguration`
- `plotTimeProfile()` ⇔ `TimeProfilePlotConfiguration`
- etc.

The exception to this is `plotResVsPred()`, which, instead of having its own `ResVsPredPlotConfiguration` class, co-opts `ObsVsPredPlotConfiguration` from `plotObsVsPred()`.

In addition to being inconsistent, this is also introducing some unnecessary implementation complications while working on https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/925.

Therefore, is it possible to introduce `ResVsPredPlotConfiguration` class for `plotResVsPred()`? 
Maybe it can be a derived class, which would also make it backward compatible?

**Comment by pchelle** [comment]
I think `ResVsPredPlotConfiguration` is already its own class: 
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/develop/R/plotconfiguration.R#L319

```r
#' @title ObsVsPredPlotConfiguration
#' @description R6 class defining the configuration of a `ggplot` object for Obs vs Pred plots
#' @export
#' @family PlotConfiguration classes
ObsVsPredPlotConfiguration <- R6::R6Class(
  "ObsVsPredPlotConfiguration",
  inherit = PlotConfiguration
)

#' @title ResVsPredPlotConfiguration
#' @description R6 class defining the configuration of a `ggplot` object for Res vs Pred/Time plots
#' @export
ResVsPredPlotConfiguration <- R6::R6Class(
  "ResVsPredPlotConfiguration",
  inherit = PlotConfiguration
)
```

**Comment by IndrajeetPatil** [comment]
Oh, I see. 

Then this is a documentation issue for `plotResVsPred()`:

![image](https://user-images.githubusercontent.com/11330453/168039432-38bf65af-efa7-4d5e-accd-fa8b5704d18e.png)
