### ISSUE TITLE
FR: Avoid manual update for the caption of time profile plot

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#264]
It's not clear to me as to why, but, the caption for `tlf::plotTimeProfile()` output needs to be manually updated using `setLegendCaption()`. This is quite tricky and error-prone. 

Is there any way that this is internally handled by the plotting function itself? 

It is a bit surprising that the caption is not automatically updated to the chosen mappings for the plot, and needs to be updated manually.

**Comment by pchelle** [comment]
@IndrajeetPatil 
Not sure I understand what you mean there, can you add an example ?

**Comment by IndrajeetPatil** [comment]
Sure.

Not sure if you remember, but we had this issue where instead of each group getting its own color, the same colors were being recycled. This is why we added [this](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/e81a5f8efa0024c0f578d5c472503ff97c6afb85/R/utilities-plotting.R#L434-L466) function that updates caption legend data frame.

Here are outputs from [this test](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/e81a5f8efa0024c0f578d5c472503ff97c6afb85/tests/testthat/test-plot-individual-time-profile.R#L57-L73) that illustrate the point. 

## Without updating legend caption data frame

(Note that there are only 3 unique colors which are used twice in the caption)

![image](https://user-images.githubusercontent.com/11330453/168030575-c5d0bd4a-8cb0-485c-882b-5cdd84c61d12.png)

## With updating legend caption data frame

![image](https://user-images.githubusercontent.com/11330453/168031596-c158082f-7b5a-4153-9bd9-37047a598390.png)
