### ISSUE TITLE
Creating a new release before `ospsuite 11` release

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#267]
The plotting functionality that will become available to the users in `ospsuite 11` release relies on the development version of _tlf_. 

So we will need to create a new release of _tlf_ before _ospsuite_, so that `ospsuite 11` can rely on this newly released _tlf_ version.

**Comment by IndrajeetPatil** [comment]
@Yuri05 I am not sure what's happening with package versioning here. 

The version on `develop`-branch is 

https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/7d1e1157a519ae066f33d0386df9bd08aaab0c53/DESCRIPTION#L4

And, yet, version 1.2.5 has already been [released](https://github.com/Open-Systems-Pharmacology/TLF-Library/releases):

![image](https://user-images.githubusercontent.com/11330453/169237284-5965f88f-3f55-4ed9-b3b6-9eb25826a749.png)

**Comment by Yuri05** [comment]
yep, forgotten to increase the version. let's make it 1.3 then
