### ISSUE TITLE
switch off gridlines

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/TLF-Library#280]
The following (activity specific) code tries to eliminate the gridlines in concentration-time plots, but does not work. How can this be solved?

mySpecificCode<-function(workflow){
  xGrid = LineElement$new()
  xGrid$linetype = "blank"
  yGrid = LineElement$new()
  yGrid$linetype = "blank"
  timeprofileplotconfiguration = TimeProfilePlotConfiguration$new(xGrid = xGrid,yGrid = yGrid)
  workflow$plotTimeProfilesAndResiduals$settings$plotConfigurations$timeProfile=timeprofileplotconfiguration
}

**Comment by Yuri05** [comment]
ok, cool. @TWendl Can you try the workaround?

**Comment by TWendl** [comment]
Thanks, the workaround was successful!
