### ISSUE TITLE
Adding horizontal error bars to `plotObsVsPred()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#327]
As specified [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/945#issuecomment-1173770611), is it possible to add a horizontal error bar for observed data in `plotObsVsPred()`? 

If this is currently not possible, can we support this?

![image](https://user-images.githubusercontent.com/11330453/177385766-50073c14-54a4-4f27-b122-86885e404d8d.png)

**Comment by pchelle** [comment]
It can be supported, `ObsVsPredDataMapping` already has inputs for __vertical__ errorbars 
> `error` if the values are symmetrical, or `ymin` and `ymax` if user defined

I guess it makes more sense to switch to horizontal bars if observed is in the x axis (by tuning the function `.parseAddUncertaintyLayer()`).

**Comment by IndrajeetPatil** [comment]
Good to know that this should be straightforward to implement. Thanks.

**Comment by pchelle** [comment]
@IndrajeetPatil 
While fixing this, I realized that the `error` field in the `DataMapping` objects is not convenient (especially, we don't if error is meant for arithmetic or geometric errors).
So, instead, I will replace `error` by `ymin` and `ymax` for most of the `DataMapping` and by `xmin` and `xmax` for `ObsVsPredDataMapping`

In a separate issue, I am going to 
- add wrappers to compute these errors
- add a vignette about working with errorbars in plots such as obs vs pred, pk and ddi ratio
