### ISSUE TITLE
Dynamic code generation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#345]
Sorry for the delay.
The variable `fillLength` is created during the call of `.parseUpdateAestheticProperty` when input argument is `"fill"`
To prevent potential copy/paste issues of very similar lines of code, most of the functions from `aaa-utilities.R` directly output R code as character strings (which are then transformed into expressions to be evaluated as actual R code using `parse(text)` and `eval(expression)`.

Below shows the expression returned when the function `.parseUpdateAestheticProperty` is called with the arguments "fill" and `ribbons`. 
```r 
> .parseUpdateAestheticProperty("fill", "ribbons")

expression(
fillVariable <- gsub("`", "", mapLabels$fill),
fillLength <- length(unique(mapData[, fillVariable])),
suppressMessages(
plotObject <- plotObject + ggplot2::scale_fill_manual(
values = .getAestheticValues(n = fillLength, selectionKey = plotConfiguration$ribbons$fill, aesthetic = "fill")
)
), 
if (isIncluded(fillVariable, "legendLabels")) {
plotObject <- plotObject + ggplot2::guides(fill = "none")
}
)
```

When the expression is wrapped by `eval()`, this code is evaluated and 
- Creates the variable `fillVariable`, column name in the data linked to the `fill` property
- Creates the variable `fillLength`, number of unique values for the `fill` property (used for selecting the right number of colors)
- Update the `fill` properties of the plot `plotObject`
- Remove the legend if no mapping was actually defined

Note that changing `"fill"` by any other property name such as `"color"` or `"alpha"` would directly create an evaluated R code with all the property names changed to `"color"` or `"alpha"`

_Originally posted by @pchelle in https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/338#discussion_r927675592_

**Comment by IndrajeetPatil** [comment]
Did you mean to close this?

I don't see what the issue was.

**Comment by Yuri05** [comment]
The issue is here: https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/346
