### ISSUE TITLE
"Dynamic" code generation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#346]
https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/338#discussion_r927675592
> The variable `fillLength` is created during the call of `.parseUpdateAestheticProperty` when input argument is `"fill"` To prevent potential copy/paste issues of very similar lines of code, most of the functions from `aaa-utilities.R` directly output R code as character strings (which are then transformed into expressions to be evaluated as actual R code using `parse(text)` and `eval(expression)`.
> 
> Below shows the expression returned when the function `.parseUpdateAestheticProperty` is called with the arguments "fill" and `ribbons`.
> 
> ```r
> > .parseUpdateAestheticProperty("fill", "ribbons")
> 
> expression(
> fillVariable <- gsub("`", "", mapLabels$fill),
> fillLength <- length(unique(mapData[, fillVariable])),
> suppressMessages(
> plotObject <- plotObject + ggplot2::scale_fill_manual(
> values = .getAestheticValues(n = fillLength, selectionKey = plotConfiguration$ribbons$fill, aesthetic = "fill")
> )
> ), 
> if (isIncluded(fillVariable, "legendLabels")) {
> plotObject <- plotObject + ggplot2::guides(fill = "none")
> }
> )
> ```
> 
> When the expression is wrapped by `eval()`, this code is evaluated and
> 
>     * Creates the variable `fillVariable`, column name in the data linked to the `fill` property
> 
>     * Creates the variable `fillLength`, number of unique values for the `fill` property (used for selecting the right number of colors)
> 
>     * Update the `fill` properties of the plot `plotObject`
> 
>     * Remove the legend if no mapping was actually defined
> 
> 
> Note that changing `"fill"` by any other property name such as `"color"` or `"alpha"` would directly create an evaluated R code with all the property names changed to `"color"` or `"alpha"`

Regarding this I have2 questions:

1) The current implementation is hard to understand (at least for me) and not easy to test.
Can we transfer `.parseUpdateAestheticProperty` (and other functions of this kind) into a "normal" functions? e.g. `.parseUpdateAestheticProperty(plotObject, plotConfiguration, aestheticProperty, plotConfigurationProperty, mapLabels, mapData)`
In the function, the settings would be extracted from the plotConfiguration and from the mapping and applied to the plot object.
So the same what the current code does but without dynamically generated expressions and calling `eval `on them

2) Regardless of whether you make this change or not: there are several places in code where `.parseUpdateAestheticProperty` is not called, e.g. here:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/cdcdd20dba79521fbdafd32ea81be2a35c72132b/R/plot-boxwhisker.R#L103-L120
or here:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/cdcdd20dba79521fbdafd32ea81be2a35c72132b/R/plot-boxwhisker.R#L103-L120
or here:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/cdcdd20dba79521fbdafd32ea81be2a35c72132b/R/plot-tornado.R#L124-L133
MAybe more...

**Comment by pchelle** [comment]
> Regardless of whether you make this change or not: there are several places in code where .parseUpdateAestheticProperty is not called

It is the biggest issue when evaluating expression instead of using the smaller function calls, the `eval` runs the whole dynamic code. Since in some plots it is not strictly identical, the `.parseXXX` could not be run.
