### ISSUE TITLE
Don't display error bar caps when there are no error bars

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#348]
Follow up on #344 

This happens when the error values are 0, and so there is no error bar displayed. But the caps are still shown.

Look at `total` and `Placebo_total` group data points:

![image](https://user-images.githubusercontent.com/11330453/180973924-09506177-9dad-4552-81b2-fcf4a2a1825a.png)

**Comment by pchelle** [comment]
Since dataMapping now uses `ymin` and `ymax` instead of `error`.
You can use `NA` values if there is no error so the cap won't show up.
I can add the argument `na.rm=TRUE` so you won't get the warning messages

**Comment by IndrajeetPatil** [comment]
Thanks! That solved the issue.
