### ISSUE TITLE
Produce the same axes limits for `plotObsVsPred()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/TLF-Library#350]
For more, see:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1051

**Comment by pchelle** [comment]
In my opinion, it is better if the (default) axes limits are handled internally by `{ospsuite}`
Then, you can provide the symmetric values to `{tlf}`
- either when you defined the default plot configuration
- or you can wrap the final plot with `setXAxis` and `setYAxis`

**Comment by IndrajeetPatil** [comment]
As discussed in the meeting, possibly add an option to make the plot symmetric.
