### ISSUE TITLE
Create enum listing available molecule plots

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/TLF-Library#374]
Until this is fixed, here is the current list of available plots are :

- Atoms
   - `initializePlot`
   - `addScatter`
   - `addLine`
   - `addRibbon`
   - `addErrorbar`
- Molecule
   - `plotPKRatio`
   - `plotDDIRatio` (with option for obs vs pred and res vs pred)
   - `plotHistogram`
   - `plotBoxWhisker`
   - `plotTornado` (with option for bar or scatter)
   - `plotObsVsPred`
   - `plotResVsPred`
   - `plotResVsTime`
   - `plotTimeProfile`
   - `plotQQ` (after PR #370 is merged)

**Comment by Yuri05** [comment]
@sfrechen @annikarps FYI

**Comment by Felixmil** [comment]
Available as `AtomPlots` and `MoleculePlots` enums.
