### ISSUE TITLE
Docu website: articles section

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#400]
I wonder, why on the [tlf website](https://www.open-systems-pharmacology.org/TLF-Library/) we don't have a dropdown menu for articles:
![grafik](https://user-images.githubusercontent.com/25061876/213420489-7e4eb910-87e3-495c-8586-93420243807e.png)

For other packages it's there, e.g. [Reporting Engine](https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/):
![grafik](https://user-images.githubusercontent.com/25061876/213420716-8562a89b-e226-4b6f-a71a-60cc7fdd60b7.png)

**Comment by PavelBal** [comment]
You have to define them separately in the _pkgdown.yml, see example from ospsuite-r:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/417a7ce692d75368a1d6e66d97aba7be65e6cc4f/_pkgdown.yml#L13
