### ISSUE TITLE
ospsuite build failing, cannot generate any figures

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/TLF-Library#427]
Simple examlpe: 

```
dsLength <- 1
dataSets <- vector("list", dsLength)
for (i in 1:dsLength){
  ds <- DataSet$new(name = paste0("ds", i))
  ds$setValues(0, 1)
  ds$addMetaData("IndividualId", as.character(i))
  dataSets[[i]] <- ds
}
myDc <- DataCombined$new()
myDc$addDataSets(dataSets)

plotIndividualTimeProfile(myDc)
```

I think this is due to changes in TLF. If not, please transfer to `ospsuite`. This must be fixed ASAP.

**Comment by pchelle** [comment]
@PavelBal , is this the error trace ?

**Comment by Felixmil** [comment]
Which versions of osps & tlf do you have installed ?

**Comment by Felixmil** [comment]
Try this:
```
#re-install rlang 
install.packages("rlang")
# re-install ggplot2 
install.packages("ggplot2")
```

[Source](https://stackoverflow.com/questions/75772757/r-for-data-science-chapter-2-2-2-already-getting-error-messages-before-ive-star)

**Comment by PavelBal** [comment]
> @PavelBal Try this:

Works. WTF, why? And why is the ospsuite-build failing then? Trying to create vignettes locally now.
