### ISSUE TITLE
Some shapes not properly displayed

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#433]
I executed an example from the online help on my machine: 
`addScatter(x = 1:10, y = rlnorm(10), shape = Shapes$pentagon, color = "blue", size = 10)`
 
The result in the online help looks good (https://www.open-systems-pharmacology.org/TLF-Library/dev/reference/Shapes.html)
 
The result on my machine was: I got open rectangles instead of pentagons. I also got open rectangles for 
•	Circle
•	pentagonOpen
•	hexagon
•	hehaxonOpen
 
All other shapes worked as expected
 
![grafik](https://user-images.githubusercontent.com/25061876/227204177-212faee9-ff8e-44d2-aba3-9ba07753c994.png)

The same happens if I show all shapes at once (again, same code as in the online help):

![grafik](https://user-images.githubusercontent.com/25061876/227204294-2e231dec-787d-4eff-b1b4-0c8bf06480a8.png)

But if I just print the shapes list: all symbols look good

![grafik](https://user-images.githubusercontent.com/25061876/227204396-3fb8b3fa-842d-41a4-b2ca-849b7400db34.png)
![grafik](https://user-images.githubusercontent.com/25061876/227204411-22b3ee2b-d0a4-419e-9fc9-21378dd8323d.png)

**Comment by PavelBal** [comment]
I have pentagons, strange...

But I just realized - we can plot sheep! xD

**Comment by PavelBal** [comment]
This is just so amazing

![image](https://user-images.githubusercontent.com/25903040/227601617-bc731657-1ddd-4bc0-8338-d2538f1c7b78.png)
