### ISSUE TITLE
`showtext` side effects

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/TLF-Library#442]
The introduction of `showtext` to include new symbols has the following side effects

- [x] displayed symbols are smaller (#437 )
- [x] displayed symbols and text all depends on `dpi` (which is 96 for R and RStudio window devices but 300 when saved to a png or pdf file)
- [x] `_` symbol for errorbar horizontal caps is not centered anymore and needs either using `geom_point()` or be replaced by unicode character `\u2501` (`━`)
- [x] default symbol aesthetic of [`geom_point()`](https://github.com/tidyverse/ggplot2/blob/d7f22413efea3dd2a7c9effff05d4b2aa2c2d300/R/geom-point.R#L116) needs to be replaced to prevent weird legend when `color` and `shape` are mapped separately
> currently, the number `19` is displayed (default ggplot2 value formerly translate as a dot) and can be replaced by unicode character `\u2588` (`█`)

**Comment by Felixmil** [comment]
Another side effect: alpha scales are ignored.
This should make points below LLOQ ~40 more transparent than base alpha level:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/1a69654d97165487ba37069070b6af26fcf13d6c/R/utilities-molecule-plots.R#L24-L42
However it is not the case anymore.

**Comment by pchelle** [comment]
@Felixmil , thanks for spotting this
I included the fix for `alpha` in PR #444
