### ISSUE TITLE
If plot labels contains ` characters, ggtext throws an error

### ISSUE THREAD

**Issue by Felixmil** [Open-Systems-Pharmacology/TLF-Library#480]
see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1277

**Comment by Yuri05** [comment]
@Felixmil Please also report as a bug to ggtext (https://github.com/wilkelab/ggtext/issues)

**Comment by Felixmil** [comment]
Already referenced here: https://github.com/wilkelab/ggtext/issues/53

It is more a limitation than a bug. Implementing the \<code> tag apparently needs implementing another rendering engine.

**Comment by Yuri05** [comment]
ok, thx for the info.
