### ISSUE TITLE
Remove unnecessary deviation ranges around dots

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/TLF-Library#498]
Aims at fixing RE issue [#1182](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/1182)

**Comment by PavelBal** [comment]
Same as here? https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1121

**Comment by pchelle** [comment]
> Same as here? [Open-Systems-Pharmacology/OSPSuite-R#1121](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1121)

Yes
