### ISSUE TITLE
Adjust mode in _pkgdown.yml

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/TLF-Library#508]
Replace `mode: devel` with `mode: !expr Sys.getenv('PKGDOWN_MODE')`
(otherwise the **update-release-website.yml** action will still update the dev website)

**Comment by pchelle** [comment]
Currently we have this:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/6bafc92b5539fe381640c4d0d623fdd83406ca18/.github/workflows/update-release-website.yml#L16

Is this not what `!expr Sys.getenv('PKGDOWN_MODE')` would also provide ?

**Comment by Yuri05** [comment]
_update-release-website.yml_ is correct; the error is in **_pkgdown.yml**:
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/6bafc92b5539fe381640c4d0d623fdd83406ca18/_pkgdown.yml#L7
