### ISSUE TITLE
Swap Groupings and GroupMapping classes

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/TLF-Library#88]
Grouping should map variables within a group
GroupMapping should map aesthetic properties to groupings
(currently the opposite)

**Comment by abdullahhamadeh** [comment]
Do you mean just swap the naming?

**Comment by pchelle** [comment]
Yes, only the naming,
Users expect the other way around because of the current naming, so swapping will prevent such confusion.
